/**
 * Result pane: renders the OCR result with fixed 3 tabs.
 *
 * Maintenance notes:
 * - Tabs are always: Markdown / Preview / TXT. They do not depend on doc.format.
 *   DOCX is available via the download button, not as a tab.
 * - Markdown / Preview read result.md (canonical source).
 * - TXT is lazily generated by the backend from result.md on first request.
 * - If a legacy document has no result.md → backend returns 404 → show
 *   preview.source_unavailable.
 * - Markdown / TXT modes → <pre> with raw text (escaped).
 * - Preview mode → HTML from the backend (sanitized via bleach).
 */

import type { Document } from './types';
import { t } from './i18n';

export type ResultTabKey = 'markdown' | 'preview' | 'text';

export interface ResultTab {
  key: ResultTabKey;
  label: string;
}

/**
 * Return the fixed 3 tabs (with current i18n labels).
 * Not a constant — labels depend on the current language, which can change at runtime.
 */
export function allResultTabs(): ResultTab[] {
  return [
    { key: 'markdown', label: t('tab.markdown') },
    { key: 'preview', label: t('tab.preview') },
    { key: 'text', label: t('tab.text') },
  ];
}

/**
 * Tab → format mapping (used by api.resultUrl and for availability checks).
 */
export const TAB_TO_FORMAT: Record<ResultTabKey, 'md' | 'txt'> = {
  markdown: 'md',
  preview: 'md',
  text: 'txt',
};

/**
 * Is a tab available for the document? (based on available_formats + md source).
 * Markdown/Preview require 'md' in available_formats.
 * TXT is available if 'md' (source for generation) OR 'txt' (already on disk).
 */
export function isTabAvailable(tab: ResultTabKey, available: string[]): boolean {
  if (tab === 'markdown' || tab === 'preview') return available.includes('md');
  if (tab === 'text') return available.includes('md') || available.includes('txt');
  return false;
}

interface ResultApi {
  getMarkdown(id: string, format?: 'md' | 'txt'): Promise<string>;
  getRendered(id: string, format?: 'md' | 'docx'): Promise<string>;
}

function escHtml(s: string): string {
  const d = document.createElement('div');
  d.textContent = s;
  return d.innerHTML;
}

function spinner(): string {
  return '<div class="text-text-muted text-center py-10"><div class="inline-block w-6 h-6 border-2 border-accent border-t-transparent rounded-full animate-spin"></div></div>';
}

export async function renderResult(
  container: HTMLElement,
  doc: Document | null,
  tab: ResultTabKey,
  api: ResultApi,
): Promise<void> {
  if (!doc) {
    container.innerHTML = `<div class="text-text-muted text-center py-10">${t('preview.empty')}</div>`;
    return;
  }
  if (doc.status !== 'done') {
    container.innerHTML = `<div class="text-text-muted text-center py-10">${t('preview.unavailable')}</div>`;
    return;
  }
  if (!isTabAvailable(tab, doc.available_formats)) {
    container.innerHTML = `<div class="text-text-muted text-center py-10">${t('preview.source_unavailable')}</div>`;
    return;
  }

  // Show spinner while loading
  container.innerHTML = spinner();
  try {
    if (tab === 'markdown') {
      const text = await api.getMarkdown(doc.id, 'md');
      container.innerHTML = `<pre class="whitespace-pre-wrap break-words text-sm font-mono leading-relaxed">${escHtml(text)}</pre>`;
    } else if (tab === 'text') {
      const text = await api.getMarkdown(doc.id, 'txt');
      container.innerHTML = `<pre class="whitespace-pre-wrap break-words text-sm font-mono leading-relaxed">${escHtml(text)}</pre>`;
    } else if (tab === 'preview') {
      const html = await api.getRendered(doc.id, 'md');
      container.innerHTML = `<div class="rendered prose prose-invert max-w-none">${html}</div>`;
    }
  } catch {
    container.innerHTML = `<div class="text-error text-center py-10">${t('preview.unavailable')}</div>`;
  }
}
